version: '3.8'

services:
  rds:
    image: redis
    container_name: rds
    ports:
      - "6379:6379"
    networks:
      - betMaker
  
  betmaker-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: betmaker-app
    ports:
      - "8000:8000"
    depends_on:
      - rds
    networks:
      - betMaker

networks:
  betMaker:
